src/java/managedBeans/HotelBookClientBean.java
/*
 * The class is coping with the client users' request
 * Then sending requests to broker server and get response from broker server.
 */
package managedBeans;

import entities.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Serializable;
import java.net.InetAddress;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import utility.Constants;
import utility.Utility;

/**
 *
 * @author Ivan Zhu <ivanzhujunwei@gmail.com>
 */
@ManagedBean(name = "hotelBookBean")
@SessionScoped
public class HotelBookClientBean implements Serializable
{

    // city name
    public String cityName;
    
    // hotel name
    public String hotelName;
    
    // hotel room rate
    public double rate;
    
    // check in date
    public String checkIn;
    
    // check out date
    public String checkOut;
    
    // available rooms found
    public List<Room> roomsFound;
    public boolean show;

    // city list displayed in drop down list
    public List<String> allCities;

    // guest name
    public String guestName;
    
    // guest phone
    public String phone;
    
    // guest email
    public String email;
    
    // guest credit
    public String credit;

    // total amount
    public double totalAmount;

    // room which is being booked
    public Room bookingRoom;

    // error response from servers
    public String error;
    
    // different connection info for hotel servers
    public String connInfoHilton;
    public String connInfoChevron;
    public String connInfoRegent;

    // establish the inputstream and outputstream
    InputStream in = null;
    PrintStream out = null;

    /**
     * Creates a new instance of HotelBookBean
     */
    public HotelBookClientBean()
    {
        allCities = new ArrayList<>();
        connInfoChevron = "";
        connInfoHilton = "";
        connInfoRegent = "";

        InetAddress address = null;
        try {
            address = InetAddress.getByName("localhost");
        } catch (UnknownHostException e) {
            e.printStackTrace();
            System.exit(2);
            return;
        }
        Socket sock = null;
        try {
            sock = new Socket(address, Constants.PORT_BROKER);
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(3);
            return;
        }
        try {
            in = sock.getInputStream();
            out = new PrintStream(sock.getOutputStream());
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(5);
            return;
        }
        System.out.println("Client Running");
    }

    @PostConstruct
    public void init()
    {
        initSessionValue();
    }

    /***
     * Initialize value
     */
    private void initSessionValue()
    {
        error = "";
        cityName = "";
        hotelName = "";
        rate = 0;
        roomsFound = new ArrayList<>();
        bookingRoom = new Room();

    }

    /**
     * *
     * Connect to different hotel servers
     *
     * @param hotelName hotel name
     */
    public void connectHotelServer(String hotelName)
    {
        // send request to server: try to connect hotel server
        out.println(Constants.POC_CONNECT_HOTEL_SERER + hotelName);
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String connectInfo = reader.readLine();
            setError("");
            switch (hotelName) {
                case Constants.HOTEL_CHEVRON:
                    connInfoChevron = connectInfo;
                    break;
                case Constants.HOTEL_HILTON:
                    connInfoHilton = connectInfo;
                    break;
                case Constants.HOTEL_REGENT:
                    connInfoRegent = connectInfo;
                    break;
                default:
                    break;
            }
        } catch (SocketException se) {
            setError("Error: connection lost, unable to connect to broker server.");
        } catch (IOException ex) {
            setError("Error: IO exception when trying to connecting to broker server.");
        }
    }

    /***
     * Find another room after booking successfully
     * @return 
     */
    public String findAnotherRoom()
    {
        initSessionValue();
        return "findAroom.xhtml";
    }

    /**
     * *
     * Get all city names
     *
     * @return city names in the form of a list
     */
    public List<String> getAllCities()
    {
        // send request to server: get all citites' name
        allCities.clear();
        out.println(Constants.POC_BROKER_ALL_CITIES);
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String line = reader.readLine();
            if (!Utility.isEmpty(line)) {
                // cities' name are seperated by comma ','
                String[] cityNames = line.split(",");
                allCities.addAll(Arrays.asList(cityNames));
            }
        } catch (SocketException se) {
            setError(Constants.ERR_BROKER_SERVER);
        } catch (IOException ex) {
            setError(Constants.ERR_IOEXCEPTION);
        }
        return allCities;
    }

    /**
     * *
     * Get hotel names by city name
     *
     * @return hotel name in the form of a list
     */
    public List<String> getHotelsInCity()
    {
        List<String> lst = new ArrayList<>();
        try {
            // correct city name
            if (cityName != null && !cityName.trim().equals("")) {
                out.println(Constants.POC_BROKER_HOTEL_FROM_CITY + cityName);
                BufferedReader reader = new BufferedReader(new InputStreamReader(in));
                String line = reader.readLine();
                clearError();
                if (!Utility.isEmpty(line)) {
                    // hotels' name are seperated by comma ','
                    String[] hotelNames = line.split(",");
                    lst.addAll(Arrays.asList(hotelNames));
                }
            }
        } catch (SocketException se) {
            setError(Constants.ERR_BROKER_SERVER);
        } catch (IOException ex) {
            setError(Constants.ERR_IOEXCEPTION);
        }
        return lst;
    }

    /**
     * *
     * Clear error context
     */
    private void clearError()
    {
        setError("");
    }

    /***
     * Get hotel rate
     * @return 
     */
    public double getRate()
    {
        String rateStr = "0";
        if (!Utility.isEmpty(hotelName) && !Utility.isEmpty(cityName)) {
            out.println(Constants.POC_BROKER_HOTEL_RATE + hotelName + ":" + cityName);
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            try {
                rateStr = reader.readLine();
                System.out.println("........"+rateStr);
                rate = Double.parseDouble(rateStr);
            } catch (SocketException se) {
                setError(Constants.ERR_BROKER_SERVER);
            } catch (IOException ex) {
                setError(Constants.ERR_IOEXCEPTION);
            }
        }
        return rate;
    }

    public List<Room> getRoomsFound()
    {
        return roomsFound;
    }

    /***
     * Make a booking 
     * @return 
     */
    public String makeBooking()
    {
        String request = Constants.POC_HOTEL_SUBMIT_BOOKING
                + hotelName + Constants.SEMI
                + checkIn + Constants.SEMI
                + checkOut + Constants.SEMI
                + bookingRoom.getRoomId() + Constants.SEMI
                + guestName + Constants.SEMI
                + phone + Constants.SEMI
                + email + Constants.SEMI
                + credit;
        out.println(request);
        BufferedReader reader = new BufferedReader(new InputStreamReader(in));
        try {
            String bookResponse = reader.readLine();
            // if hotel servers send response with failure information
            // booking operation will be prevented
            if (Utility.isErrorFromServer(bookResponse)) {
                setError(bookResponse);
                return "bookRoom.xhtml";
            } else {
                clearError();
            }
        } catch (SocketException se) {
            setError(Constants.ERR_BROKER_SERVER);
        } catch (IOException ex) {
            setError(Constants.ERR_IOEXCEPTION);
        }
        return "ticket.xhtml";
    }

    /***
     * Find available rooms
     */
    public void getAvailableRooms()
    {
        if (Utility.isEmpty(hotelName) || Utility.isEmpty(checkIn) || Utility.isEmpty(checkOut)) {
            return;
        }
        // validate checkin and checkout order
        if (!Utility.strDateCompare(checkIn, checkOut)) {
            setError("Check in date should be before check out date.");
            return;
        } else {
            clearError();
        }
        if (Utility.isDateFormat(checkIn) && Utility.isDateFormat(checkOut)) {
            // hotelName could only be: HOTEL_BROKER / HOTEL_HILTON / HOTEL_CHEVRON / HOTEL_REGENT
            String request = Constants.POC_HOTEL_AVAILABLE_ROOMS + hotelName + ":" + checkIn + ":" + checkOut;
            out.println(request);
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String roomFromServer;
            try {
                roomsFound.clear();
                roomFromServer = reader.readLine();

web/bookRoom.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>
        <ui:composition template="template.xhtml">
            <ui:define name="title">
                Hotel broker
            </ui:define>
            <ui:define name="box">
                <h4>Welcome to hotel booking broker!</h4><br/>
                <h:form>
                    <div class="col-lg-10">
                        <div class="panel panel-default ">
                            <div class="panel-heading">Booking info</div>
                            <div class="panel-body">
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">City</label>
                                    <div class="col-lg-4 ">
                                        <label class="control-label">#{hotelBookBean.cityName}</label>
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Hotel</label>
                                    <div class="col-lg-4 ">
                                        <label class="control-label">#{hotelBookBean.hotelName}</label>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Room rate</label>
                                    <div class="col-lg-4" >
                                        $<label class="control-label">#{hotelBookBean.rate}</label>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Total amount</label>
                                    <div class="col-lg-4" >
                                        $<label class="control-label">#{hotelBookBean.totalAmount}</label>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Check in</label>
                                    <div class="col-lg-4" >
                                        <label class="control-label">#{hotelBookBean.checkIn}</label>
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Check out</label>
                                    <div class="col-lg-4">
                                        <label class="control-label">#{hotelBookBean.checkOut}</label>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-10" >
                        <div class="panel panel-default " >
                            <div class="panel-heading">Fill in customer's information <label class="inputError">#{hotelBookBean.error}</label></div>
                            <div class="panel-body">
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Guest name</label>
                                    <div class="col-lg-4 inputWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.guestName}"
                                                      id="guestname"
                                                      required="true" requiredMessage="Guest name cannot be empty"/>
                                    </div>
                                    <label class="col-lg-3 control-label"><h:message class="inputError" for="guestname"></h:message></label>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Contact phone</label>
                                    <div class="col-lg-4 inputWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.phone}"
                                                      id="phone"
                                                      required="true" requiredMessage="Phone cannot be empty"
                                                      validatorMessage = "6 number for phone">
                                            <f:validateRegex pattern="\d{6}"></f:validateRegex>
                                        </h:inputText>
                                    </div>
                                    <label class="col-lg-3 control-label"><h:message class="inputError" for="phone"></h:message></label>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Contact email</label>
                                    <div class="col-lg-4 inputWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.email}"
                                                      id="email"
                                                      required="true" requiredMessage="Email cannot be empty" 
                                                      validatorMessage="Incorrect email">
                                             <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                                        </h:inputText>
                                    </div>
                                    <label class="col-lg-3 control-label"><h:message class="inputError" for="email"></h:message></label>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-2 control-label">Credit number</label>
                                    <div class="col-lg-4 inputWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.credit}"
                                                      id="credit"
                                                      required="true" requiredMessage="Credit cannot be empty" validatorMessage="10 number for credit">
                                            <f:validateRegex pattern="\d{10}"></f:validateRegex>
                                        </h:inputText>
                                    </div>
                                    <label class="col-lg-3 control-label"><h:message class="inputError" for="credit"></h:message></label>
                                </div>
                                <div class="form-group col-lg-2 ">
                                <h:commandLink class="btn btn-success " style="width:320px;margin-left: 14px;margin-top: 10px;" value="Confirm and Book" 
                                               action="#{hotelBookBean.makeBooking()}">
                                    &nbsp;&nbsp;<i class="fa fa-key"></i>
                                </h:commandLink>
                            </div>
                            </div>
                        </div>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
    <script>
      
    </script>
</html>

web/configConnection.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >

    <body>
        <ui:composition template="template.xhtml">
            <ui:define name="title">
                Hotel broker
            </ui:define>
            <ui:define name="box">
                <h:form>
                    <div class="col-md-12" style="padding-bottom: 20px;padding-top:20px;">
                        <div class="col-md-9">
                            <h4>Welcome to hotel booking broker!</h4><label class="inputError">#{hotelBookBean.error}</label>
                        </div>
                        <div class="col-md-3">
                            <h:commandLink class="btn btn-success"  style="text-align: right" action="findAroom">Find rooms in connected hotels</h:commandLink>
                        </div>

                    </div>
                    <br/>
                    <div class="row col-md-12">

                        <div class="col-xs-6 col-md-4">
                            <h:commandLink class="thumbnail" style="height: 300px" action="#{hotelBookBean.connectHotelServer('Chevron')}">
                                <img src="img/chevron.png"/>
                            </h:commandLink>
                            <div class="col-12-6 col-12-4">
                                #{hotelBookBean.connInfoChevron}
                            </div>
                        </div>
                        <div class="col-xs-6 col-md-4">
                            <h:commandLink  class="thumbnail" style="height: 300px" action="#{hotelBookBean.connectHotelServer('Hilton')}">
                                <img src="img/hilton.png" />
                            </h:commandLink>
                            <div class="col-12-6 col-12-4">
                                #{hotelBookBean.connInfoHilton}
                            </div>
                        </div>
                        <div class="col-xs-6 col-md-4">
                            <h:commandLink class="thumbnail" style="height: 300px" action="#{hotelBookBean.connectHotelServer('Regent')}">
                                <img src="img/regent.jpg" />
                            </h:commandLink>
                            <div class="col-12-6 col-12-4">
                                #{hotelBookBean.connInfoRegent}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
    <script>
    </script>
</html>

web/findAroom.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" 
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

    <body>
        <ui:composition template="template.xhtml">
            <ui:define name="title">
                Hotel broker
            </ui:define>
            <ui:define name="box">
                <h:form id="header">
                    <div class="col-md-12" style="padding-bottom: 20px;padding-top:20px;">
                        <div class="col-md-10">
                            <h4>Welcome to hotel booking broker!</h4>
                        </div>
                        <div class="col-md-2">
                            <h:commandLink action="configConnection" class="btn btn-warning" ><i class="fa fa-"></i>Configure</h:commandLink>
                        </div>
                    </div>
                    <br/>
                </h:form>
                <h:form>
                    <div class="col-lg-6">
                        <div class="panel panel-default ">
                            <div class="panel-heading">Find you holiday
                                <h:message style="color: red" for="checkin" />&nbsp;
                                <h:message style="color: red" for="checkout" />
                                <label class="inputError">#{hotelBookBean.error}</label>
                            </div>
                            <div class="panel-body">
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-5 control-label">Choose a city</label>
                                    <div class="col-lg-7 selectWithLabel">
                                        <h:selectOneMenu id="selectCity" class="form-control" style="height:35px"
                                                         value="#{hotelBookBean.cityName}">
                                            <f:selectItem  itemLabel = " - Select a city "/>
                                            <f:selectItems value="#{hotelBookBean.getAllCities()}" />
                                            <f:ajax execute="selectCity" render="selectHotel"/>
                                        </h:selectOneMenu>
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-5 control-label">Choose a hotel</label>
                                    <div class="col-lg-7 selectWithLabel">
                                        <h:selectOneMenu id="selectHotel" class="form-control" style="height:35px" value="#{hotelBookBean.hotelName}" >
                                            <f:selectItem  itemLabel = " - Select a hotel "/>
                                            <f:selectItems value="#{hotelBookBean.hotelsInCity}" />
                                            <f:ajax   execute="selectHotel"  render="rateId" />
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-5 control-label">Room rate</label>
                                    <div class="col-lg-7 selectWithLabel"  >
                                        $<h:outputText id="rateId" value="#{hotelBookBean.rate}" />
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-5 control-label">Check in</label>
                                    <div class="col-lg-7 selectWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.checkIn}" a:placeholder="yyyy-mm-dd"  id="checkin"
                                                      required="true" requiredMessage="Check in date cannot be empty"  
                                                      validatorMessage="Date format should be yyyy-mm-dd" >
                                            <f:validateRegex pattern="\d{4}[-]\d{2}[-]\d{2}"></f:validateRegex>
                                        </h:inputText>
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 ">
                                    <label class="col-lg-5 control-label">Check out</label>
                                    <div class="col-lg-7 selectWithLabel" >
                                        <h:inputText  class="form-control" value="#{hotelBookBean.checkOut}" a:placeholder="yyyy-mm-dd" id="checkout"
                                                      required="true" requiredMessage="Check out date cannot be empty" 
                                                      validatorMessage="Date format should be yyyy-mm-dd" >
                                            <f:validateRegex pattern="\d{4}[-]\d{2}[-]\d{2}"></f:validateRegex>
                                        </h:inputText>
                                    </div>
                                </div>

                                <div class="form-group col-lg-5 ">
                                    <h:commandLink class="btn btn-success searchRoom"  value="Search" action="#{hotelBookBean.getAvailableRooms()}" >
                                        &nbsp;&nbsp;<i class="fa fa-search"></i>
                                        <!--<f:ajax   execute="@form"  render="roomsForBooking" />-->
                                    </h:commandLink>
                                </div>
                            </div>
                        </div>
                    </div>
                </h:form>
                <div class="col-lg-5">
                    <div class="panel panel-default" style="height: 353px">
                        <div class="panel-heading">Available rooms<br/>
                        </div>
                        <div class="panel-body">
                            <h:form id="MyForm">
                                <table class="table table-striped">
                                    <tr>
                                        <th width="10%"> RoomNO. </th>
                                        <th width="80%"> Description </th>
                                        <th width="10%">  </th>
                                    </tr>
                                    <!-- For each service in service list... --> 
                                    <div></div>
                                    <ui:repeat id="roomsForBooking" value="#{hotelBookBean.roomsFound}" var="room" varStatus="status"> 
                                        <tr> 
                                            <td style="vertical-align: middle">  
                                                <h:outputText value="#{room.roomId}" id="room_id" />  
                                            </td>
                                            <td style="vertical-align: middle"> <h:outputText value="#{room.des}"  /></td>
                                            <td style="vertical-align: middle"> 
                                                <h:commandLink action="#{hotelBookBean.tryBooking(room)}"><i class="fa fa-info-circle"></i>
                                                </h:commandLink>
                                            </td>
                                        </tr> 
                                    </ui:repeat> 
                                </table>
                            </h:form>
                        </div>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </body>
    <script>
        function dateCompare() {
            alert(3);
        }
    </script>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="css/stylesheet.css" rel="stylesheet" type="text/css" />
        <!-- Bootstrap -->
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet"></link>
        <script src="js/jquery-3.1.1.js"></script>
        <link 
            href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
            rel="stylesheet"  type='text/css'></link>
        <title><ui:insert name="title">Facelets Template</ui:insert></title>
    </h:head>

    <h:body>
        <div id="mainContainer">
            <div id="left" class="col-lg-12">
                <ui:insert name="box">Box Content Here</ui:insert>
            </div>
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="bootstrap/js/bootstrap.min.js"></script>
    </h:body>

</html>